# Generated by Django 3.0.1 on 2019-12-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_uz', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('position_ru', models.CharField(max_length=255)),
                ('position_uz', models.CharField(max_length=255)),
                ('position_en', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=255)),
                ('receive_days_ru', models.CharField(max_length=255)),
                ('receive_days_uz', models.CharField(max_length=255)),
                ('receive_days_en', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'management',
            },
        ),
    ]
