# Generated by Django 3.0.1 on 2019-12-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_ru', models.TextField()),
                ('content_uz', models.TextField()),
                ('content_en', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.News')),
            ],
            options={
                'db_table': 'news_files',
            },
        ),
    ]
