# Generated by Django 2.2.9 on 2019-12-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news_newsfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.TextField(blank=True, null=True)),
                ('name_uz', models.TextField(blank=True, null=True)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('code', models.TextField()),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.TextField()),
                ('title_uz', models.TextField()),
                ('title_en', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='gallery/photo/')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.TextField()),
                ('title_ru', models.TextField()),
                ('title_uz', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('description_uz', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.TextField()),
                ('title_uz', models.TextField()),
                ('title_en', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(upload_to='gallery/video/')),
                ('video', models.FileField(upload_to='gallery/video/')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='news/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_ru', models.TextField(blank=True, null=True)),
                ('content_uz', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
            ],
            options={
                'db_table': 'map_datas',
            },
        ),
    ]
