# Generated by Django 2.2.9 on 2019-12-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.TextField()),
                ('description_ru', models.TextField()),
                ('title_uz', models.TextField()),
                ('description_uz', models.TextField()),
                ('title_en', models.TextField()),
                ('description_en', models.TextField()),
                ('element1_title_ru', models.TextField()),
                ('element1_title_uz', models.TextField()),
                ('element1_title_en', models.TextField()),
                ('element1_value', models.TextField()),
                ('element2_title_ru', models.TextField()),
                ('element2_title_uz', models.TextField()),
                ('element2_title_en', models.TextField()),
                ('element2_value', models.TextField()),
                ('element3_title_ru', models.TextField()),
                ('element3_title_uz', models.TextField()),
                ('element3_title_en', models.TextField()),
                ('element3_value', models.TextField()),
                ('element4_title_ru', models.TextField()),
                ('element4_title_uz', models.TextField()),
                ('element4_title_en', models.TextField()),
                ('element4_value', models.TextField()),
            ],
            options={
                'db_table': 'numbers',
            },
        ),
    ]
