# Generated by Django 2.2.9 on 2019-12-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.TextField(blank=True, null=True)),
                ('name_uz', models.TextField(blank=True, null=True)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('title_ru', models.TextField()),
                ('title_uz', models.TextField()),
                ('title_en', models.TextField()),
                ('content_ru', models.TextField()),
                ('content_en', models.TextField()),
                ('content_uz', models.TextField()),
            ],
            options={
                'db_table': 'tickers',
            },
        ),
    ]
