# Generated by Django 2.2.9 on 2019-12-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name_ru', models.TextField()),
                ('author_name_uz', models.TextField()),
                ('author_name_en', models.TextField()),
                ('position_ru', models.TextField()),
                ('position_uz', models.TextField()),
                ('position_en', models.TextField()),
                ('content_ru', models.TextField()),
                ('content_uz', models.TextField()),
                ('content_en', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'quotes',
            },
        ),
    ]
